### ISSUE TITLE
使用-oe -od参数时写入偶尔值为空会报错

### ISSUE THREAD

**Issue by gongcsxue** [Ifory885/fshzqSearch#2]
Traceback (most recent call last):
  File "fshzqSearch.py", line 18, in <module>
    search = Search(args, keyword)
  File "F:\temp\fshzqSearch-main\lib\search.py", line 31, in __init__
    self.modular(result)
  File "F:\temp\fshzqSearch-main\lib\search.py", line 40, in modular
    data.showScreen()       # 屏幕打印
  File "F:\temp\fshzqSearch-main\lib\process.py", line 27, in showScreen
    for res in self.result:

**Comment by Ifory885** [comment]
是不是fofa接口报的错，可能为fofa API的问题。

**Comment by Ifory885** [comment]
> Traceback (most recent call last): File "fshzqSearch.py", line 18, in search = Search(args, keyword) File "F:\temp\fshzqSearch-main\lib\search.py", line 31, in **init** self.modular(result) File "F:\temp\fshzqSearch-main\lib\search.py", line 40, in modular data.showScreen() # 屏幕打印 File "F:\temp\fshzqSearch-main\lib\process.py", line 27, in showScreen for res in self.result:

是不是fofa接口报的错，可能为fofa API的问题，现在已经好了
